# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=234)),
                ('amount', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('datetime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf.Rollup')),
            ],
        ),
    ]
