# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_auto_20171125_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
