# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0006_auto_20171227_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='Location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='events',
            name='name',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
