# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0007_auto_20171227_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cost',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
