# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0008_events_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golfername', models.CharField(default='none', max_length=200)),
                ('score', models.CharField(default='0', max_length=6)),
                ('handicap', models.CharField(default='0', max_length=6)),
            ],
        ),
    ]
