# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0009_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
